#!/usr/bin/env bash
# write-prime-snapshots.sh
# Writes Projects/<slug>-state.md for every active project — the file the
# `/prime` command in this vault looks for (matched via frontmatter
# `local_path: <cwd>` to identify the previous-session context).
#
# Reuses project-iteration logic and skip rules from
# scripts/propagate-frontend-policy.sh:
#   - Top-level Projects/*.md only
#   - Skip _*, README*, *-state files, archived (status: archived)
#   - Skip empty/missing local_path
#   - Skip if local_path directory doesn't exist
#
# v2 (2026-05-04) — marker-based managed section:
#   The canonical body is wrapped in
#       <!-- BEGIN: PRIME-MANAGED-STATE ... --> ... <!-- END: PRIME-MANAGED-STATE -->
#   markers. Everything outside the markers (frontmatter + user-added
#   sections like ## Deploy status, ## Skills, ## Vault knowledge) is
#   preserved across runs. Idempotency is content-based (byte-compare on
#   the assembled output), not date-based, so re-running on a different
#   day after the same content does NOT destroy preserved sections.
#
#   Migration path for legacy state files (no markers) is handled
#   automatically: the script detects the legacy "## Verification …
#   visible-content-checklist" anchor and rewraps the canonical body in
#   markers while preserving everything that follows.
#
# Usage:
#   ./scripts/write-prime-snapshots.sh --dry-run --verbose
#   ./scripts/write-prime-snapshots.sh --only novashop
#   ./scripts/write-prime-snapshots.sh                       # writes for real
#
# Compatible with bash 3.2 (macOS system bash).

set -euo pipefail

VAULT="/Users/aleksejpravotorov/Desktop/My AI Knowledge Base"
PROJECTS_DIR="$VAULT/Projects"
SESSION_TAG="frontend-skill-policy"
TODAY="$(date '+%Y-%m-%d')"

BEGIN_MARKER='<!-- BEGIN: PRIME-MANAGED-STATE (auto-generated by write-prime-snapshots.sh — do not edit between markers) -->'
END_MARKER='<!-- END: PRIME-MANAGED-STATE -->'
# Final line of the canonical body — used to detect & migrate legacy files.
LEGACY_ANCHOR='Before marking visual work complete, walk the project through `qa/visible-content-checklist.md` (5 yes/no checks) at vault root.'

DRY_RUN=0
VERBOSE=0
ONLY=""

while [ $# -gt 0 ]; do
  case "$1" in
    --dry-run) DRY_RUN=1 ;;
    --verbose|-v) VERBOSE=1 ;;
    --only)
      shift
      ONLY="${1:-}"
      if [ -z "$ONLY" ]; then
        echo "ERROR: --only requires a slug argument" >&2
        exit 2
      fi
      ;;
    -h|--help)
      /usr/bin/sed -n '2,/^$/p' "$0" | /usr/bin/sed 's/^# \{0,1\}//'
      exit 0
      ;;
    *)
      echo "ERROR: unknown flag: $1" >&2
      exit 2
      ;;
  esac
  shift
done

log() {
  if [ "$VERBOSE" = "1" ]; then echo "$*" >&2; fi
}

COUNT_WRITTEN=0
COUNT_NOOP=0
COUNT_MIGRATED=0
COUNT_SKIP=0
ERRORS=0
MATCHED_ONLY=0

if [ -n "$ONLY" ]; then
  if [ ! -f "$PROJECTS_DIR/$ONLY.md" ]; then
    echo "ERROR: --only slug '$ONLY' did not match any project note in $PROJECTS_DIR" >&2
    exit 1
  fi
fi

# Same frontmatter extractor as propagate-frontend-policy.sh.
get_frontmatter_value() {
  local file="$1" key="$2"
  /usr/bin/awk -v k="$key" '
    BEGIN { in_fm = 0 }
    NR == 1 && /^---[[:space:]]*$/ { in_fm = 1; next }
    in_fm && /^---[[:space:]]*$/ { exit }
    in_fm {
      if (match($0, "^[[:space:]]*" k "[[:space:]]*:[[:space:]]*")) {
        v = substr($0, RLENGTH + 1)
        sub(/[[:space:]]+$/, "", v)
        if (v ~ /^".*"$/) { v = substr(v, 2, length(v) - 2) }
        else if (v ~ /^\x27.*\x27$/) { v = substr(v, 2, length(v) - 2) }
        print v
        exit
      }
    }
  ' "$file"
}

render_frontmatter() {
  local slug="$1" local_path="$2"
  cat <<FM
---
type: project-state
slug: $slug
local_path: $local_path
last_updated: $TODAY
session: $SESSION_TAG
---
FM
}

# Quoted heredoc for the body (no expansion); markers emitted via echo so the
# heredoc can keep its backticks/$ unmolested.
render_managed_block() {
  echo "$BEGIN_MARKER"
  cat <<'MB'
# Last session — Frontend Skill Policy rollout (2026-04-28)

## What changed
- SPSS (Single Primary Style Skill) policy is now active for this project. Canonical: `/Users/aleksejpravotorov/Desktop/My AI Knowledge Base/FRONTEND_SKILL_POLICY.md`.
- Project's `CLAUDE.md` has a managed block between `<!-- BEGIN: FRONTEND_SKILL_POLICY -->` markers — reference, do not edit between markers.

## Active baseline
- shadcn/ui + Tailwind. All effect/animation skills DORMANT until explicitly invoked.

## Dormant lane (require explicit trigger)
- `/svg-animations`, `/algorithmic-art`, `/scroll-animations`, `/framer-motion`, `/gsap`, `/three.js`
- Or natural-language: "add scroll animation", "use GSAP", "premium design system palette", etc. (see policy §4a strong signals)

## Z-index contract (cheat sheet)
- Decorative bg: `z ≤ 0` + `pointer-events:none` (full-viewport decorative MUST have both)
- Chrome: `1-9` OR `z-50` for sticky app frame (canonical `<header className="sticky top-0 z-50">` allowed)
- Content: `10-19`
- Functional overlays (Radix Dialog/Sheet/AlertDialog, vaul Drawer, cmdk): platform default `z-50` with `pointer-events:auto` — exempt from decorative rule

## Skills outside policy scope
- `json-render`, `knowledge-update`, session reminders, functional auto-fire co-load (nextjs + next-cache-components + react-best-practices + agent-browser-verify) — cannot be suppressed; mitigate by keeping styling minimal.

## Verification
Before marking visual work complete, walk the project through `qa/visible-content-checklist.md` (5 yes/no checks) at vault root.
MB
  echo "$END_MARKER"
}

render_default_post_managed() {
  cat <<'POST'

## Next session
Pick up project work normally. The policy auto-loads via this state file + the managed CLAUDE.md block.
POST
}

# Extract everything that should be PRESERVED from an existing state file —
# i.e., everything that is neither the frontmatter nor the managed body.
extract_preserved_zone() {
  local file="$1" mode="$2"
  case "$mode" in
    marker)
      # Skip frontmatter, skip the structural-separator blank lines between
      # frontmatter and BEGIN marker, skip everything between BEGIN/END
      # (inclusive). Print everything after END.
      /usr/bin/awk -v bm="$BEGIN_MARKER" -v em="$END_MARKER" '
        BEGIN { fm_count = 0; in_block = 0; seen_begin = 0 }
        /^---[[:space:]]*$/ {
          fm_count++
          if (fm_count <= 2) next
        }
        fm_count < 2 { next }
        $0 == bm { in_block = 1; seen_begin = 1; next }
        in_block && $0 == em { in_block = 0; next }
        in_block { next }
        !seen_begin { next }
        { print }
      ' "$file"
      ;;
    legacy)
      /usr/bin/awk -v anchor="$LEGACY_ANCHOR" '
        BEGIN { fm_count = 0; past_anchor = 0 }
        /^---[[:space:]]*$/ {
          fm_count++
          if (fm_count <= 2) next
        }
        fm_count < 2 { next }
        past_anchor { print }
        index($0, anchor) > 0 { past_anchor = 1 }
      ' "$file"
      ;;
    body)
      # Unknown format — preserve all body (we will prepend the managed
      # block; user can re-arrange manually if desired).
      /usr/bin/awk '
        BEGIN { fm_count = 0 }
        /^---[[:space:]]*$/ {
          fm_count++
          if (fm_count <= 2) next
        }
        fm_count < 2 { next }
        { print }
      ' "$file"
      ;;
  esac
}

process_project() {
  local note="$1"
  local base="${note##*/}"
  base="${base%.md}"

  case "$base" in
    _*|README|readme|Readme)
      log "skip: $base (system file)"
      COUNT_SKIP=$((COUNT_SKIP + 1))
      return 0
      ;;
    *-state)
      log "skip: $base (already a state file)"
      COUNT_SKIP=$((COUNT_SKIP + 1))
      return 0
      ;;
  esac

  if [ -n "$ONLY" ] && [ "$base" != "$ONLY" ]; then
    return 0
  fi

  local status local_path
  status=$(get_frontmatter_value "$note" "status")
  local_path=$(get_frontmatter_value "$note" "local_path")

  if [ "$status" = "archived" ]; then
    log "skip: $base (status=archived)"
    COUNT_SKIP=$((COUNT_SKIP + 1))
    return 0
  fi
  if [ -z "$local_path" ]; then
    log "skip: $base (no local_path in frontmatter)"
    COUNT_SKIP=$((COUNT_SKIP + 1))
    return 0
  fi
  if [ ! -d "$local_path" ]; then
    log "skip: $base (local_path does not exist: $local_path)"
    COUNT_SKIP=$((COUNT_SKIP + 1))
    return 0
  fi

  if [ -n "$ONLY" ]; then MATCHED_ONLY=1; fi

  local state_file="$PROJECTS_DIR/$base-state.md"

  # Build expected components into tempfiles.
  local fm_tmp mb_tmp pres_tmp out_tmp
  fm_tmp=$(/usr/bin/mktemp -t prime-fm.XXXXXX)
  mb_tmp=$(/usr/bin/mktemp -t prime-mb.XXXXXX)
  pres_tmp=$(/usr/bin/mktemp -t prime-pres.XXXXXX)
  out_tmp=$(/usr/bin/mktemp -t prime-out.XXXXXX)

  render_frontmatter "$base" "$local_path" > "$fm_tmp"
  render_managed_block > "$mb_tmp"

  local file_mode=""
  if [ -f "$state_file" ]; then
    if /usr/bin/grep -qF "$BEGIN_MARKER" "$state_file" \
       && /usr/bin/grep -qF "$END_MARKER" "$state_file"; then
      file_mode="marker"
    elif /usr/bin/grep -qF "$LEGACY_ANCHOR" "$state_file"; then
      file_mode="legacy"
    else
      file_mode="body"
    fi
    extract_preserved_zone "$state_file" "$file_mode" > "$pres_tmp"
  fi

  # Compose the new file: frontmatter + blank line + managed block + preserved zone.
  {
    /bin/cat "$fm_tmp"
    /bin/echo
    /bin/cat "$mb_tmp"
    if [ -s "$pres_tmp" ]; then
      /bin/cat "$pres_tmp"
    else
      render_default_post_managed
    fi
  } > "$out_tmp"

  # Idempotency: byte-compare new candidate against existing.
  if [ -f "$state_file" ] && /usr/bin/cmp -s "$out_tmp" "$state_file"; then
    log "noop: $state_file (already current)"
    COUNT_NOOP=$((COUNT_NOOP + 1))
    /bin/rm -f "$fm_tmp" "$mb_tmp" "$pres_tmp" "$out_tmp"
    return 0
  fi

  if [ "$DRY_RUN" = "1" ]; then
    if [ -f "$state_file" ]; then
      if [ "$file_mode" = "legacy" ] || [ "$file_mode" = "body" ]; then
        log "DRY: would migrate $state_file ($file_mode → marker)"
      else
        log "DRY: would update $state_file"
      fi
    else
      log "DRY: would create $state_file"
    fi
    COUNT_WRITTEN=$((COUNT_WRITTEN + 1))
    /bin/rm -f "$fm_tmp" "$mb_tmp" "$pres_tmp" "$out_tmp"
    return 0
  fi

  # Size sanity — refuse 0-byte writes.
  local new_size
  new_size=$(/usr/bin/wc -c < "$out_tmp" | /usr/bin/tr -d ' ')
  if [ "$new_size" -le 0 ]; then
    echo "ERROR: refusing to write empty state file for $base" >&2
    /bin/rm -f "$fm_tmp" "$mb_tmp" "$pres_tmp" "$out_tmp"
    ERRORS=$((ERRORS + 1))
    return 0
  fi

  # If existing file is non-trivial, refuse to shrink by >70%.
  if [ -f "$state_file" ]; then
    local orig_size
    orig_size=$(/usr/bin/wc -c < "$state_file" | /usr/bin/tr -d ' ')
    if [ "$orig_size" -gt 200 ]; then
      local threshold=$(( orig_size * 30 / 100 ))
      if [ "$new_size" -lt "$threshold" ]; then
        echo "ERROR: refusing to write $base — output ($new_size B) is <30% of original ($orig_size B)" >&2
        /bin/rm -f "$fm_tmp" "$mb_tmp" "$pres_tmp" "$out_tmp"
        ERRORS=$((ERRORS + 1))
        return 0
      fi
    fi
  fi

  /bin/mv "$out_tmp" "$state_file"
  if [ "$file_mode" = "legacy" ] || [ "$file_mode" = "body" ]; then
    log "MIGRATE: $state_file ($file_mode → marker)"
    COUNT_MIGRATED=$((COUNT_MIGRATED + 1))
  else
    log "WRITE: $state_file"
  fi
  COUNT_WRITTEN=$((COUNT_WRITTEN + 1))
  /bin/rm -f "$fm_tmp" "$mb_tmp" "$pres_tmp"
}

if [ ! -d "$PROJECTS_DIR" ]; then
  echo "ERROR: Projects dir not found: $PROJECTS_DIR" >&2
  exit 2
fi

shopt -s nullglob
for note in "$PROJECTS_DIR"/*.md; do
  [ -f "$note" ] || continue
  process_project "$note"
done
shopt -u nullglob

if [ -n "$ONLY" ] && [ "$MATCHED_ONLY" -eq 0 ]; then
  echo "ERROR: --only slug '$ONLY' matched a note but the project was filtered out" >&2
  exit 1
fi

MODE="LIVE"
[ "$DRY_RUN" = "1" ] && MODE="DRY-RUN"
echo ""
echo "[$MODE] States written: $COUNT_WRITTEN (migrated: $COUNT_MIGRATED) | NoOp: $COUNT_NOOP | Skipped: $COUNT_SKIP | Errors: $ERRORS"

if [ "$ERRORS" -gt 0 ]; then
  exit 1
fi
exit 0
